apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: exam2025
        image: gcr.io/exam-458209/exam2025:latest
        imagePullPolicy: ALWAYS
        ports:
        - containerPort: 5000
        env:
          - name: GCP_BUCKET_NAME
            value: "alvaro-bucket-1"
        livenessProbe:
          periodSeconds: 2
          httpGet:
            path: /
            port: 80


